version: '3.8'

services:
  mysql:
    image: mysql:8.4
    container_name: outbox-pattern-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: outbox_db
      MYSQL_USER: outbox_user
      MYSQL_PASSWORD: outbox_password
      MYSQL_ROOT_PASSWORD: root_password
    volumes:
      - ./mysql_data:/var/lib/mysql
      - ./migrations:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - outbox-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u outbox_user -poutbox_password"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  outbox-network:
    driver: bridge

volumes:
  mysql_data:

